Algoritmo "mediadetresnumeros"
//descrição  :  calcula a media de tres numeros
//autor      :  Victor Marques
//data       :  08/03/2022
Var

n1,n2,n3,media: real

Inicio
//entrada
escreval("Digite o primeiro numero")
leia(n1)
escreval("Digite o segundo numero")
leia(n2)
escreval("Digite o terceiro numero")
leia(n3)

//processamento
media <- (n1+n2+n3)/3

//saida
escreval("A media dos tres numeros é:", media)



Fimalgoritmo